logging:
  level: INFO
  loggers:
    com.mycompany: DEBUG

server:
  adminConnectors:
    -
      port: 8081
      type: http
  adminContextPath: /admin
  applicationConnectors:
    -
      port: 8080
      type: http
  rootPath: /api/*